DBMRecategoryDefinitionV2 = {
  Recat_FirstAid_Smoking = {
    "Base.Cigarillo",
    "Base.CanPipe",
    "Base.CanPipe_Tobacco",
    "Base.TobaccoChewing",
    "Base.Cigar",
    "Base.CigaretteSingle",
    "Base.CigaretteCarton",
    "Base.CigarettePack",
    "Base.TobaccoLoose",
    "Base.CigaretteRolled",
    "Base.SmokingPipe_Tobacco",
  },
  Recat_Electrical_Material = {
    "Base.Amplifier",
    -- "Base.Battery",  -- Maybe some consumable
    -- "Base.BatteryBox",
    "Base.LightBulb",
    "Base.LightBulbBlue",
    "Base.LightBulbCyan",
    "Base.LightBulbGreen",
    "Base.LightBulbMagenta",
    "Base.LightBulbOrange",
    "Base.LightBulbPink",
    "Base.LightBulbPurple",
    "Base.LightBulbRed",
    "Base.LightBulbYellow",
    "Base.LightBulbBox",
    "Base.ElectricWire",
    "Base.RadioReceiver",
    "Base.RadioTransmitter",
    "Base.Receiver",
    "Base.ElectronicsScrap",
  },
  Recat_LiquidContainer_Small = {
    "Base.MayonnaiseEmpty",
    "Base.PlasticCup",
    "Base.Canteen",
    "Base.CanteenMilitaryFull",
    "Base.CanteenClay",
    "Base.CanteenMilitary",
    "Base.BeerCanEmpty",
    "Base.BeerBottle",
    "Base.BeerCan",
    "Base.Pop",
    "Base.Pop2",
    "Base.Pop3",
  },
  Recat_LiquidContainer_Medium = {
    "Base.HotWaterBottle",
    "Base.Bag_LeatherWaterBag",
    "Base.BeerEmpty",
    "Base.JuiceOrange",
    "Base.JuiceGrape",
    "Base.JuiceFruitpunch",
    "Base.JuiceCranberry",
    "Base.MilkBottle",
    "Base.PopBottleRare",
    "Base.JuiceTomato",
    "Base.SimpleSyrup",
    "Base.JuiceLemon",
    "Base.WineAged",
    "Base.Whiskey",
    "Base.WineBox",
    "Base.Brandy",
    "Base.Champagne",
    "Base.WineScrewtop",
    "Base.Cider",
  },
  Recat_LiquidContainer_Large = {
    "Base.PaintbucketEmpty",
    "Base.Bucket",
    "Base.BucketForged",
    "Base.BucketEmpty",
    "Base.BucketCarved",
    "Base.WaterDispenserBottle",
  },
  Recat_Food_Imperishable = {
    "Base.DriedApricots",
    "Base.CandyFruitSlices",
    "Base.Candycane",
    "Base.CandyCorn",
    "Base.TinnedBeans",
    "Base.CannedCarrots2",
    "Base.CannedChili",
    "Base.CannedCorn",
    "Base.CannedCornedBeef",
    "Base.Dogfood",
    "Base.CannedMilk",
    "Base.CannedFruitBeverage",
    "Base.CannedFruitCocktail",
    "Base.CannedMushroomSoup",
    "Base.CannedPeaches",
    "Base.CannedPeas",
    "Base.CannedPineapple",
    "Base.CannedPotato2",
    "Base.CannedSardines",
    "Base.CannedBolognese",
    "Base.CannedTomato2",
    "Base.TunaTin",
    "Base.TinnedSoup",
    "Base.CandyCaramels",
    "Base.CatTreats",
    "Base.Cereal",
    "Base.Crisps",
    "Base.Crisps2",
    "Base.Crisps3",
    "Base.Crisps4",
    "Base.ChocoCakes",
    "Base.Chocolate_Candy",
    "Base.CookieChocolateChip",
    "Base.ChocolateChips",
    "Base.CookiesChocolate",
    "Base.ChocolateCoveredCoffeeBeans",
    "Base.Chocolate_Butterchunkers",
    "Base.Cone",
    "Base.Crackers",
    "Base.Chocolate_Crackle",
    "Base.CookiesShortbread",
    "Base.Chocolate_Smirkers",
    "Base.Chocolate_SnikSnak",
    "Base.SnoGlobes",
    "Base.MysteryCan",
    "Base.CandiedApple",
    "Base.CandyPackage",
    "Base.CinnamonRoll",
    "Base.Lollipop",
    -- TBD
  },
  Recat_Food_Perishable = {

  },
  Recat_Food_Seasoning = {
    "Base.Capers",
    -- TBD
  },
}
