DBMRecategoryDefinitionV2 = {
  Recat_FirstAid_Smoking = {
    "Base.Cigarillo",
    "Base.CanPipe",
    "Base.CanPipe_Tobacco",
    "Base.TobaccoChewing",
    "Base.Cigar",
    "Base.CigaretteSingle",
    "Base.CigaretteCarton",
    "Base.CigarettePack",
    "Base.TobaccoLoose",
    "Base.CigaretteRolled",
    "Base.SmokingPipe_Tobacco",
  },
  Recat_Material_Electronics = {
    "Base.Amplifier",
    -- "Base.Battery",  -- Maybe some consumable
    -- "Base.BatteryBox",
    "Base.LightBulb",
    "Base.LightBulbBlue",
    "Base.LightBulbCyan",
    "Base.LightBulbGreen",
    "Base.LightBulbMagenta",
    "Base.LightBulbOrange",
    "Base.LightBulbPink",
    "Base.LightBulbPurple",
    "Base.LightBulbRed",
    "Base.LightBulbYellow",
    "Base.LightBulbBox",
    "Base.ElectricWire",
    "Base.RadioReceiver",
    "Base.RadioTransmitter",
    "Base.Receiver",
    "Base.ElectronicsScrap",
  },
  Recat_LiquidContainer_Small = {
    "Base.MayonnaiseEmpty",
    "Base.PlasticCup",
  },
  Recat_LiquidContainer_Medium = {
    "Base.HotWaterBottle",
    "Base.Bag_LeatherWaterBag",
  },
  Recat_LiquidContainer_Large = {
    "Base.PaintbucketEmpty",
  },
  Recat_Food_Imperishable = {
    "Base.DriedApricots",
    "Base.CandyFruitSlices",
    "Base.Candycane",
    "Base.CandyCorn",
    "Base.TinnedBeans",
    "Base.CannedCarrots2",
    "Base.CannedChili",
    "Base.CannedCorn",
    "Base.CannedCornedBeef",
    "Base.Dogfood",
    "Base.CannedMilk",
    "Base.CannedFruitBeverage",
    "Base.CannedFruitCocktail",
    "Base.CannedMushroomSoup",
    "Base.CannedPeaches",
    "Base.CannedPeas",
    "Base.CannedPineapple",
    "Base.CannedPotato2",
    "Base.CannedSardines",
    "Base.CannedBolognese",
    "Base.CannedTomato2",
  },
}
